apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - command: ["/usr/local/bin/etcd", "-advertise-client-urls", "http://0.0.0.0:2379", "-listen-client-urls", "http://0.0.0.0:2379"]
          image: "rancher/mirrored-coreos-etcd:v3.4.15-rancher1"
          imagePullPolicy: IfNotPresent
          name: etcd
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 10Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  ports:
    - name: tcp2379
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: tcp2380
      port: 2380
      protocol: TCP
      targetPort: 2380
  selector:
    app: etcd
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-keeper
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: etcd-keeper
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: etcd-keeper
    spec:
      containers:
        - image: "showurl/etcdkeeper:v0.7.6"
          command: ["/bin/sh", "-c", "/etcdkeeper/etcdkeeper || /opt/etcdkeeper/etcdkeeper.bin -h $HOST -p $PORT"]
          imagePullPolicy: Always
          name: etcd-keeper
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 10Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: remote-etcd-keeper
spec:
  ports:
    - nodePort: 8083
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: etcd-keeper
  type: NodePort

