apiVersion: apps/v1
kind: Deployment
metadata:
  name: msgtransfer-history-cassandra
  namespace: zeroim
  labels:
    app: msgtransfer-history-cassandra
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: msgtransfer-history-cassandra
  template:
    metadata:
      labels:
        app: msgtransfer-history-cassandra
    spec:
      serviceAccountName: find-endpoints
      containers:
      - name: msgtransfer-history-cassandra
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: ZEROIM_SERVICECONF__NAME
            value: msgtransfer-history-cassandra
          - name: ZEROIM_SERVICECONF_LOG__SERVICENAME
            value: msgtransfer-history-cassandra
          - name: ZEROIM_SERVICECONF_TELEMETRY__NAME
            value: msgtransfer-history-cassandra
          - name: ZEROIM_CASSANDRA_CASSANDRACONFIG__CONSISTENCY
            value: ONE
        envFrom:
          - configMapRef:
              name: zeroim-configmap
        image: ccr.ccs.tencentyun.com/zeroim/msgtransfer-history-cassandra:20220528184807
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 60Mi
          limits:
            cpu: 100m
            memory: 60Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      imagePullSecrets:
      - name: registry
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: msgtransfer-history-cassandra-svc
  namespace: zeroim
spec:
  ports:
    - port: 80
  selector:
    app: msgtransfer-history-cassandra

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: msgtransfer-history-cassandra-hpa-c
  namespace: zeroim
  labels:
    app: msgtransfer-history-cassandra-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: msgtransfer-history-cassandra
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: msgtransfer-history-cassandra-hpa-m
  namespace: zeroim
  labels:
    app: msgtransfer-history-cassandra-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: msgtransfer-history-cassandra
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
