apiVersion: v1
data:
  CASSANDRA_HOST: "10.42.0.190"
  CASSANDRA_PORT: "9042"
  CASSANDRA_USERNAME: "cassandra"
  CASSANDRA_PASSWORD: "cassandra"
kind: ConfigMap
metadata:
  name: cassandra-web-configmap

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cassandra-web
  template:
    metadata:
      labels:
        app: cassandra-web
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: cassandra-web-configmap
          image: markusgulden/cassandra-web:latest
          command:
            - cassandra-web
            - --host=$(CASSANDRA_HOST)
            - --port=$(CASSANDRA_PORT)
            - --username=$(CASSANDRA_USERNAME)
            - --password=$(CASSANDRA_PASSWORD)
          imagePullPolicy: IfNotPresent
          name: cassandra-web
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 200Mi
            requests:
              cpu: 20m
              memory: 20Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-web
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: cassandra-web
  type: ClusterIP
