---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-headless
spec:
  clusterIP: None
  ports:
    - port: 9042
    - port: 7000
  selector:
    app: cassandra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  ports:
    - port: 9042
      targetPort: 9042
      name: client
    - port: 7000
      targetPort: 7000
      name: jmx
  type: ClusterIP
  selector:
    app: cassandra