---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap
data:
  CASSANDRA_CLUSTER_NAME: "pathim"
  HEAP_NEWSIZE: "512M"
  MAX_HEAP_SIZE: "512M"
  JVM_OPTS: "-Xms512M -Xmx512M"
  CASSANDRA_SEEDS: "cassandra-0.cassandra.cassandra.svc.cluster.local"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - image: "cassandra:4.0.4"
          envFrom:
            - configMapRef:
                name: cassandra-configmap
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CASSANDRA_BROADCAST_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CASSANDRA_SEEDS
              valueFrom:
                configMapKeyRef:
                  name: cassandra-configmap
                  key: CASSANDRA_SEEDS
          ports:
            - name: p7000
              protocol: TCP
              containerPort: 7000
            - name: p9042
              protocol: TCP
              containerPort: 9042
          imagePullPolicy: IfNotPresent
          name: cassandra
          readinessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 25
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/cassandra
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data
      apiVersion: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: nfs-provisioner
---
